REM INSERTING into EVENTTYPE
SET DEFINE OFF;
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (1,'Duel',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (2,'Foul',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (3,'Free Kick',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (4,'Goalkeeper leaving line',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (5,'Interruption',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (6,'Offside',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (7,'Others on the ball',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (8,'Pass',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (9,'Save attempt',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (95,'Shot',null);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (10,'Air duel',1);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (11,'Ground attacking duel',1);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (12,'Ground defending duel',1);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (13,'Ground loose ball duel',1);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (20,'Foul',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (21,'Hand foul',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (22,'Late card foul',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (23,'Out of game foul',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (24,'Protest',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (25,'Simulation',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (26,'Time lost foul',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (27,'Violent Foul',2);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (30,'Corner',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (31,'Free Kick',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (32,'Free kick cross',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (33,'Free kick shot',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (34,'Goal kick',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (35,'Penalty',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (36,'Throw in',3);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (40,'Goalkeeper leaving line',4);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (50,'Ball out of the field',5);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (51,'Whistle',5);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (70,'Acceleration',7);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (71,'Clearance',7);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (72,'Touch',7);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (80,'Cross',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (81,'Hand pass',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (82,'Head pass',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (83,'High pass',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (84,'Launch',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (85,'Simple pass',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (86,'Smart pass',8);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (90,'Reflexes',9);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (91,'Save attempt',9);
Insert into EVENTTYPE (TYPEID,TYPENAME,SUPERTYPEID) values (100,'Shot',95);
