REM INSERTING into TEAM
SET DEFINE OFF;
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (674,'Valencia','Valencia Club de Fútbol','Valencia',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (675,'Real Madrid','Real Madrid Club de Fútbol','Madrid',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (676,'Barcelona','FC Barcelona','Barcelona',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (677,'Deportivo La Coruña','Real Club Deportivo de La Coruña','A Coruña',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (678,'Athletic Club','Athletic Club Bilbao','Bilbao',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (679,'Atlético Madrid','Club Atlético de Madrid','Madrid',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (680,'Sevilla','Sevilla FC','Sevilla',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (682,'Villarreal','Villarreal Club de Fútbol','Villarreal',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (683,'Málaga','Málaga Club de Fútbol','Malaga',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (684,'Real Betis','Real Betis Balompié','Sevilla',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (687,'Real Sociedad','Real Sociedad de Fútbol','Donostia-San Sebastián',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (691,'Espanyol','Reial Club Deportiu Espanyol','Barcelona',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (692,'Celta de Vigo','Real Club Celta de Vigo','Vigo',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (695,'Levante','Levante UD','Valencia',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (696,'Deportivo Alavés','Deportivo Alavés','Vitoria-Gasteiz',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (698,'Getafe','Getafe Club de Fútbol','Getafe (Madrid)',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (701,'Eibar','SD Eibar','Eibar',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (712,'Leganés','CD Leganés','Leganés',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (714,'Las Palmas','UD Las Palmas','Las Palmas de Gran Canaria',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (756,'Girona','Girona FC','Girona',724,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1598,'Spain','Spain','Las Rozas',724,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1609,'Arsenal','Arsenal FC','London',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1610,'Chelsea','Chelsea FC','London',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1611,'Manchester United','Manchester United FC','Manchester',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1612,'Liverpool','Liverpool FC','Liverpool',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1613,'Newcastle United','Newcastle United FC','Newcastle upon Tyne',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1619,'Southampton','Southampton FC','Southampton, Hampshire',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1623,'Everton','Everton FC','Liverpool',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1624,'Tottenham Hotspur','Tottenham Hotspur FC','London',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1625,'Manchester City','Manchester City FC','Manchester',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1627,'West Bromwich Albion','West Bromwich Albion FC','West Bromwich',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1628,'Crystal Palace','Crystal Palace FC','London',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1631,'Leicester City','Leicester City FC','Leicester',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1633,'West Ham United','West Ham United FC','London',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1639,'Stoke City','Stoke City FC','Stoke-on-Trent',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1644,'Watford','Watford FC','Watford',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1646,'Burnley','Burnley FC','Burnley, Lancashire',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1651,'Brighton & Hove Albion','Brighton & Hove Albion FC','Brighton, East Sussex',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1659,'AFC Bournemouth','AFC Bournemouth','Bournemouth, Dorset',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (1673,'Huddersfield Town','Huddersfield Town FC','Huddersfield, West Yorkshire',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2413,'England','England','London',0,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2443,'Werder Bremen','SV Werder Bremen','Bremen',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2444,'Bayern München','FC Bayern München','München',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2445,'Stuttgart','VfB Stuttgart 1893','Stuttgart',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2446,'Bayer Leverkusen','TSV Bayer 04 Leverkusen','Leverkusen',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2447,'Borussia Dortmund','BV Borussia 09 Dortmund','Dortmund',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2449,'Schalke 04','FC Schalke 04','Gelsenkirchen',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2450,'Hamburger SV','Hamburger SV','Hamburg',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2451,'Wolfsburg','VfL Wolfsburg','Wolfsburg',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2453,'Freiburg','SC Freiburg','Freiburg im Breisgau',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2454,'Borussia M''gladbach','Borussia VfL Mönchengladbach','Mönchengladbach',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2455,'Hannover 96','Hannover 96','Hannover',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2457,'Hertha BSC','Hertha BSC','Berlin',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2460,'Mainz 05','1. FSV Mainz 05','Mainz',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2462,'Eintracht Frankfurt','Eintracht Frankfurt','Frankfurt am Main',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2463,'Köln','1. FC Köln','Köln',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2481,'Augsburg','FC Augsburg','Augsburg',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2482,'Hoffenheim','TSG 1899 Hoffenheim','Sinsheim',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (2975,'RB Leipzig','Rasen Ballsport Leipzig','Leipzig',276,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3148,'Germany','Germany','Frankfurt am Main',276,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3157,'Milan','AC Milan','Milano',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3158,'Roma','AS Roma','Roma',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3159,'Juventus','Juventus FC','Torino',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3161,'Internazionale','FC Internazionale Milano','Milano',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3162,'Lazio','SS Lazio','Formello',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3163,'Udinese','Udinese Calcio','Udine',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3164,'Sampdoria','UC Sampdoria','Genova',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3165,'Chievo','AC Chievo Verona','Verona',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3166,'Bologna','Bologna FC 1909','Bologna',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3172,'Atalanta','Atalanta Bergamasca Calcio','Ciserano',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3173,'Cagliari','Cagliari Calcio','Cagliari',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3176,'Fiorentina','ACF Fiorentina','Firenze',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3185,'Torino','Torino FC','Torino',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3187,'Napoli','SSC Napoli','Castel Volturno',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3193,'Genoa','Genoa CFC','Genova',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3194,'Hellas Verona','Hellas Verona FC','Verona',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3197,'Crotone','FC Crotone','Crotone',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3204,'SPAL','Società Polisportiva Ars et Labor 2013','Ferrara',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3219,'Benevento','Benevento Calcio','Benevento',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3315,'Sassuolo','US Sassuolo Calcio','Sassuolo',380,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3757,'Italy','Italy','Roma',380,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3766,'Olympique Lyonnais','Olympique Lyonnais','Lyon',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3767,'PSG','Paris Saint-Germain FC','Paris',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3770,'Nantes','FC Nantes','La Chapelle-sur-Erdre',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3771,'Olympique Marseille','Olympique de Marseille','Marseille',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3772,'Bordeaux','FC Girondins de Bordeaux','Le Haillan',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3774,'Rennes','Stade Rennais FC','Rennes',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3775,'Nice','O.G.C. Nice Côte d''Azur','Nice',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3776,'Lille','Lille OSC Métropole','Villeneuve-d''Ascq',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3777,'Metz','FC Metz','Metz',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3779,'Strasbourg','RC Strasbourg Alsace','Strasbourg',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3780,'Toulouse','Toulouse FC','Toulouse',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3782,'Saint-Étienne','AS Saint-Étienne','Saint-Étienne',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3783,'Caen','Stade Malherbe Caen','Caen',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3785,'Guingamp','En Avant Guingamp','Guingamp',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3787,'Montpellier','Montpellier HSC','Montpellier',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3789,'Amiens SC','Amiens SC','Amiens',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3795,'Troyes','Espérance Sportive Troyes Aube Champagne','Troyes',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3799,'Angers','Angers SCO','Angers',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (3804,'Dijon','Dijon FCO','Dijon',250,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (4418,'France','France','Paris',250,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (4687,'Turkey','Turkey','Istanbul',792,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (5629,'Belgium','Belgium','Bruxelles (Brussel)',56,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (6380,'Brazil','Brazil','Rio de Janeiro, Rio de Janeiro',76,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (6697,'Switzerland','Switzerland','Bern',756,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (7047,'Sweden','Sweden','Solna',752,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (7712,'Denmark','Denmark','Brøndby',208,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (7839,'Iceland','Iceland','Reykjavík',352,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (8274,'Republic of Ireland','Republic of Ireland','Dublin',372,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (8493,'Australia','Australia','Sydney',36,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (8731,'Albania','Albania','Tiranë (Tirana)',8,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (9109,'Austria','Austria','Wien',40,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (9598,'Croatia','Croatia','Zagreb',191,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (9905,'Portugal','Portugal','Lisboa',620,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (10451,'Hungary','Hungary','Budapest',348,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (10531,'Swansea City','Swansea City AFC','Swansea',0,'club');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (10682,'Wales','Wales','Cardiff',0,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (10840,'Iran','Iran','Tehrān (Teheran)',364,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (10962,'Northern Ireland','Northern Ireland','Belfast',0,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (11555,'Czech Republic','Czech Republic','Praha',203,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (11944,'Romania','Romania','Bucureşti',642,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (12274,'Argentina','Argentina','Buenos Aires, Ciudad de Buenos Aires',32,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (12430,'Colombia','Colombia','Bogotá D.C.',170,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (12913,'Japan','Japan','Tōkyō (Tokyo)',392,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (13869,'Poland','Poland','Warszawa',616,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (14358,'Russia','Russia','Moskva',643,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (14496,'Slovakia','Slovakia','Bratislava',703,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (14622,'Ukraine','Ukraine','Kyiv (Kiev)',804,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (14855,'Korea Republic','Korea Republic','Seoul',410,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (15473,'Mexico','Mexico','Coyoacán, Ciudad de México (D.F.)',484,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (15594,'Peru','Peru','Lima',604,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (15670,'Uruguay','Uruguay','Montevideo',858,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (16129,'Egypt','Egypt','Cairo',818,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (16216,'Morocco','Morocco','Rabat',504,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (16276,'Tunisia','Tunisia','El Menzah',788,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (16521,'Saudi Arabia','Saudi Arabia','Ar-Riyāḍ (Riyadh)',682,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (16823,'Nigeria','Nigeria','Abuja',566,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (16871,'Costa Rica','Costa Rica','San José',188,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (17322,'Serbia','Serbia','Beograd',688,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (17929,'Panama','Panama','Ciudad de Panamá',591,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (19314,'Senegal','Senegal','Dakar',686,'national');
Insert into TEAM (TEAMID,NAME,OFFICIALNAME,CITY,AREAID,TYPE) values (19830,'Monaco','AS Monaco FC','Monaco',492,'club');
