
--DROP USER soccer1 CASCADE;

CREATE USER soccer1 IDENTIFIED BY soccer1;
GRANT CONNECT TO soccer1;
GRANT RESOURCE TO soccer1;
GRANT CREATE VIEW TO soccer1;

ALTER USER soccer1 DEFAULT TABLESPACE users;
ALTER USER soccer1 QUOTA 1G ON users;
ALTER USER soccer1 TEMPORARY TABLESPACE temp;

