SET TERM ON
SET SERVEROUTPUT ON

EXECUTE  DBMS_OUTPUT.PUT_LINE('Creating Soccer Tables ...');
SET TERM OFF

CREATE TABLE "AREAS" (	
    "AREAID"     NUMBER(10,0), 
	"NAME"       VARCHAR2(250 BYTE), 
	"ALPHA2CODE" VARCHAR2(10 BYTE), 
	"ALPHA3CODE" VARCHAR2(10 BYTE)
   )
;

CREATE TABLE "COMPETITION" (	
    "COMPETITIONID" NUMBER(10,0), 
	"NAME"          VARCHAR2(250 BYTE), 
	"FORMAT"        VARCHAR2(250 BYTE), 
	"AREAID"        NUMBER(10,0), 
	"TYPE"          VARCHAR2(250 BYTE)
   )
;

CREATE TABLE "TEAM" (	
    "TEAMID"       NUMBER(10,0), 
	"NAME"         VARCHAR2(250 BYTE), 
	"OFFICIALNAME" VARCHAR2(250 BYTE), 
	"CITY"         VARCHAR2(250 BYTE), 
	"AREAID"       NUMBER(10,0), 
	"TYPE"         VARCHAR2(250 BYTE)
   )
;

CREATE TABLE "COACH" (	
    "COACHID"        NUMBER(10,0), 
	"FIRSTNAME"      VARCHAR2(250 BYTE), 
	"MIDDLENAME"     VARCHAR2(250 BYTE), 
	"LASTNAME"       VARCHAR2(250 BYTE), 
	"SHORTNAME"      VARCHAR2(250 BYTE), 
	"BIRTHDATE"      DATE, 
	"CURRENTTEAMID"  NUMBER(10,0), 
	"BIRTHAREAID"    NUMBER(10,0), 
	"PASSPORTAREAID" NUMBER(10,0)
   )
;

CREATE TABLE "PLAYER" (	
    "PLAYERID"              NUMBER(10,0), 
	"FIRSTNAME"             VARCHAR2(250 BYTE), 
	"MIDDLENAME"            VARCHAR2(250 BYTE), 
	"LASTNAME"              VARCHAR2(250 BYTE), 
	"SHORTNAME"             VARCHAR2(250 BYTE), 
	"BIRTHDATE"             DATE, 
	"BIRTHAREAID"           NUMBER(10,0), 
	"PASSPORTAREAID"        NUMBER(10,0), 
	"HEIGHT"                NUMBER(3,0), 
	"FOOT"                  VARCHAR2(10 BYTE), 
	"CURRENTTEAMID"         NUMBER(10,0), 
	"CURRENTNATIONALTEAMID" NUMBER(10,0), 
	"ROLEID"                NUMBER(10,0)
   )
;

CREATE TABLE "PLAYERROLE" (	
    "ROLEID" NUMBER(10,0), 
	"NAME"    VARCHAR2(250 BYTE), 
	"CODE2"   VARCHAR2(10 BYTE), 
	"CODE3"   VARCHAR2(10 BYTE)
   )
;

CREATE TABLE "REFEREE" (	
    "REFEREEID"     NUMBER(10,0), 
	"FIRSTNAME"       VARCHAR2(250 BYTE), 
	"MIDDLENAME"      VARCHAR2(250 BYTE), 
	"LASTNAME"        VARCHAR2(250 BYTE), 
	"SHORTNAME"       VARCHAR2(250 BYTE), 
	"BIRTHDATE"       DATE, 
	"BIRTHAREAID"     NUMBER(10,0), 
	"PASSPORTAREAID"  NUMBER(10,0)
    )
;

CREATE TABLE "MATCH" (
    "MATCHID"     NUMBER(10,0), 
	"ROUNDID"       NUMBER(10,0), 
	"SEASONID"      NUMBER(10,0), 
	"COMPETITIONID" NUMBER(10,0), 
	"STATUS"        VARCHAR2(250 BYTE), 
	"WINNER"        NUMBER(10,0), 
	"GAMEWEEK"      NUMBER(10,0), 
	"VENUE"         VARCHAR2(250 BYTE), 
	"LABEL"         VARCHAR2(250 BYTE), 
	"DATEUTC"       TIMESTAMP (6), 
	"DATE_TZ"       TIMESTAMP WITH TIME ZONE, 
	"DURATION"      VARCHAR2(26 BYTE)
   )
;

CREATE TABLE "MATCHTEAM" (
    "MATCHID" NUMBER(10,0), 
	"TEAMID"    NUMBER(10,0), 
	"COACHID"   NUMBER(10,0), 
	"SIDE"      VARCHAR2(250 BYTE), 
	"SCORE"     NUMBER(10,0), 
	"SCOREHT"   NUMBER(10,0), 
	"SCOREET"   NUMBER(10,0), 
	"SCOREP"    NUMBER(10,0),
  "WINNER"    VARCHAR2(25 BYTE)
   )
;

CREATE TABLE "MATCHPLAYER" (	
    "MATCHID"   NUMBER(10,0), 
	"TEAMID"      NUMBER(10,0), 
	"PLAYERID"    NUMBER(10,0), 
	"GOALS"       NUMBER(10,0), 
	"OWNGOALS"    NUMBER(10,0), 
	"REDCARDS"    NUMBER(10,0), 
	"YELLOWCARDS" NUMBER(10,0), 
	"FORMATION"   VARCHAR2(250 BYTE)
   )
;

CREATE TABLE "MATCHREFEREE" (	
    "MATCHID" NUMBER(10,0), 
	"REFEREEID" NUMBER(10,0), 
	"ROLE"      VARCHAR2(250 BYTE)
   )
;

CREATE TABLE "MATCHSUBSTITUTION" (
    "MATCHID"   NUMBER(10,0), 
	"TEAMID"      NUMBER(10,0), 
	"PLAYERINID"  NUMBER(10,0), 
	"PLAYEROUTID" NUMBER(10,0), 
	"MINUTE"      NUMBER(10,0)
   )
;

CREATE TABLE "POSITION" (	
    "ID" NUMBER(10,0), 
	"Y"    NUMBER(10,0), 
	"X"    NUMBER(10,0)
   )
;

CREATE TABLE "EVENTTYPE" (	
    "TYPEID"    NUMBER(10,0), 
	"TYPENAME"    VARCHAR2(250 BYTE), 
	"SUPERTYPEID" NUMBER(10,0)
   )
;

CREATE TABLE "EVENTSUBTYPE" (	
    "TYPEID"    NUMBER(10,0), 
	"TYPENAME"    VARCHAR2(250 BYTE), 
	"SUPERTYPEID" NUMBER(10,0)
   )
;

CREATE TABLE "EVENT" (	
    "EVENTID"       NUMBER(10,0), 
	"MATCHID"         NUMBER(10,0), 
	"TEAMID"          NUMBER(10,0), 
	"PLAYERID"        NUMBER(10,0), 
	"MATCHPERIOD"     VARCHAR2(250 BYTE), 
	"EVENTSEC"        NUMBER(10,3), 
	"POSAID"          NUMBER(10,0), 
	"EVENTTYPEID"     NUMBER(10,0), 
	"POSBID"          NUMBER(10,0)
   )
;

SET TERM ON
EXECUTE  DBMS_OUTPUT.PUT_LINE('Tables created.');