DROP VIEW matchteam_vw;

DROP TABLE "EVENT";
DROP TABLE "EVENTSUBTYPE";
DROP TABLE "EVENTTYPE";
DROP TABLE "POSITION";
DROP TABLE "MATCHSUBSTITUTION";
DROP TABLE "MATCHREFEREE";
DROP TABLE "MATCHPLAYER";
DROP TABLE "MATCHTEAM";
DROP TABLE "MATCH";
DROP TABLE "REFEREE";
DROP TABLE "PLAYER";
DROP TABLE "PLAYERROLE";
DROP TABLE "COACH";
DROP TABLE "TEAM";
DROP TABLE "COMPETITION";
DROP TABLE "AREAS";
