TRUNCATE TABLE "EVENT";
TRUNCATE TABLE "EVENTSUBTYPE";
TRUNCATE TABLE "EVENTTYPE";
TRUNCATE TABLE "POSITION";
TRUNCATE TABLE "MATCHSUBSTITUTION";
TRUNCATE TABLE "MATCHREFEREE";
TRUNCATE TABLE "MATCHPLAYER";
TRUNCATE TABLE "MATCHTEAM";
TRUNCATE TABLE "MATCH";
TRUNCATE TABLE "REFEREE";
TRUNCATE TABLE "PLAYERROLE";
TRUNCATE TABLE "PLAYER";
TRUNCATE TABLE "COACH";
TRUNCATE TABLE "TEAM";
TRUNCATE TABLE "COMPETITION";
TRUNCATE TABLE "AREAS";

